apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-config
spec:
  chart:
    spec:
      version: 4.12.1
  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-pls-visibility: "${SUBSCRIPTION_ID}"
          service.beta.kubernetes.io/azure-pls-auto-approval: "${SUBSCRIPTION_ID}"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "${LOAD_BALANCER_SUBNET}"
      image:
        repository: "${SHARED_CONTAINER_REGISTRY}.azurecr.io/image/ingress-nginx"
        digest: "sha256:466e6b255d776c237286f013efe14da1477b172a2f444ca6806d66c9fad27111"
        tag: 1.12.1
      replicaCount: 3
      podDisruptionBudget:
        minAvailable: 2
      admissionWebhooks:
        patch:
          enabled: true
          image:
            repository: "${SHARED_CONTAINER_REGISTRY}.azurecr.io/image/kube-webhook-certgen"
            digest: "sha256:8178d256be118c19488a9e8bbd46bdeb8a984c30f0e275a1695cbbd0d75b384b"
            tag: v1.5.3
