apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: test-repository
  namespace: flux-system
spec:
  interval: 60m
  ref:
    branch: main
  url: ssh://git@github.com/defra-adp-sandpit/adp-flux-services/