apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: services-repository
  namespace: flux-config
spec:
  interval: 3m0s
  ref:
    branch: pp/kustomization
  url: ssh://git@github.com/defra-adp-sandpit/adp-flux-services/
  secretRef:
    name: adp-platform-secrets