---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: cluster-config
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: 0.18.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  values:
    defaultBackend:
      nodeSelector:
        kubernetes.io/os: "linux"
    controller:
      nginxplus: true
      image:
        repository: "ssvcdoinfcr3401.azurecr.io/image/nginx-plus-ingress"
        tag: 3.2.0
      service:
        create: true
        type: LoadBalancer
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-pls-create: "true"
      nodeSelector:
        kubernetes.io/os: "linux"