---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: infra-config
spec:
  chart:
    spec:
      chart: nginx-ingress
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-ingress
      version: 0.18.1
  install:
    createNamespace: true
  interval: 1m0s
  releaseName: nginx-ingress
  targetNamespace: nginx-ingress
  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-pls-create: "true"
        type: LoadBalancer
